micronaut:
  application:
    name: micronaut-example
  ssl:
    enabled: true
    buildSelfSigned: true
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: OzndvivjzzPMwMgqcSOfuIVUYVYUYUvUYvUYv
              jws-algorithm: HS256
eureka:
  client:
    registration:
      enabled: false
    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
endpoints:
  beans:
    enabled: true
    sensitive: false
mongodb:
  uri: mongodb://localhost:27017
  database: exampledb